// Versículo do dia — lista curada de passagens edificantes (tradução Almeida,
// domínio público). A escolha é determinística pela data: o mesmo versículo
// aparece o dia inteiro e muda a cada dia, percorrendo a lista em ciclo.

export interface Versiculo {
  referencia: string;
  texto: string;
}

export const VERSICULOS: Versiculo[] = [
  { referencia: "Filipenses 4:13", texto: "Posso todas as coisas naquele que me fortalece." },
  { referencia: "Josué 1:9", texto: "Sê forte e corajoso; não temas, nem te espantes, porque o Senhor teu Deus é contigo por onde quer que andares." },
  { referencia: "Salmos 23:1", texto: "O Senhor é o meu pastor; nada me faltará." },
  { referencia: "Provérbios 3:5", texto: "Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento." },
  { referencia: "Isaías 41:10", texto: "Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus; eu te fortaleço, e te ajudo." },
  { referencia: "Jeremias 29:11", texto: "Porque eu bem sei os pensamentos que penso de vós, pensamentos de paz e não de mal, para vos dar o fim que esperais." },
  { referencia: "Salmos 46:1", texto: "Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia." },
  { referencia: "Mateus 6:33", texto: "Buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas." },
  { referencia: "Romanos 8:28", texto: "Todas as coisas contribuem juntamente para o bem daqueles que amam a Deus." },
  { referencia: "Salmos 121:1-2", texto: "Elevo os meus olhos para os montes; de onde me vem o socorro. O meu socorro vem do Senhor, que fez o céu e a terra." },
  { referencia: "1 Coríntios 13:4", texto: "O amor é sofredor, é benigno; o amor não é invejoso; o amor não trata com leviandade, não se ensoberbece." },
  { referencia: "João 3:16", texto: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna." },
  { referencia: "Salmos 37:5", texto: "Entrega o teu caminho ao Senhor; confia nele, e ele o fará." },
  { referencia: "Provérbios 16:3", texto: "Confia ao Senhor as tuas obras, e teus pensamentos serão estabelecidos." },
  { referencia: "Filipenses 4:6", texto: "Não estejais inquietos por coisa alguma; antes as vossas petições sejam em tudo conhecidas diante de Deus." },
  { referencia: "Salmos 118:24", texto: "Este é o dia que fez o Senhor; regozijemo-nos, e alegremo-nos nele." },
  { referencia: "Mateus 11:28", texto: "Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei." },
  { referencia: "Salmos 34:8", texto: "Provai, e vede que o Senhor é bom; bem-aventurado o homem que nele confia." },
  { referencia: "Isaías 40:31", texto: "Os que esperam no Senhor renovarão as suas forças, subirão com asas como águias." },
  { referencia: "Salmos 19:14", texto: "Sejam agradáveis as palavras da minha boca e a meditação do meu coração perante a tua face, Senhor." },
  { referencia: "Provérbios 17:17", texto: "Em todo o tempo ama o amigo, e para a hora da angústia nasce o irmão." },
  { referencia: "Colossenses 3:23", texto: "E, tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor e não aos homens." },
  { referencia: "Salmos 27:1", texto: "O Senhor é a minha luz e a minha salvação; a quem temerei?" },
  { referencia: "1 João 4:19", texto: "Nós o amamos a ele porque ele nos amou primeiro." },
  { referencia: "Gálatas 5:22", texto: "O fruto do Espírito é: amor, gozo, paz, longanimidade, benignidade, bondade, fé, mansidão, temperança." },
  { referencia: "Salmos 139:14", texto: "Eu te louvarei, porque de um modo assombroso, e tão maravilhoso fui feito; maravilhosas são as tuas obras." },
  { referencia: "Provérbios 22:6", texto: "Instrui o menino no caminho em que deve andar, e até quando envelhecer não se desviará dele." },
  { referencia: "Efésios 4:32", texto: "Sede uns para com os outros benignos, misericordiosos, perdoando-vos uns aos outros." },
  { referencia: "Salmos 91:1", texto: "Aquele que habita no esconderijo do Altíssimo, à sombra do Onipotente descansará." },
  { referencia: "Mateus 5:9", texto: "Bem-aventurados os pacificadores, porque eles serão chamados filhos de Deus." },
  { referencia: "Salmos 55:22", texto: "Lança o teu cuidado sobre o Senhor, e ele te susterá." },
  { referencia: "Provérbios 15:1", texto: "A resposta branda desvia o furor, mas a palavra dura suscita a ira." },
  { referencia: "1 Tessalonicenses 5:11", texto: "Consolai-vos uns aos outros, e edificai-vos uns aos outros." },
  { referencia: "Salmos 100:5", texto: "Porque o Senhor é bom, e eterna a sua misericórdia; e a sua verdade dura de geração em geração." },
  { referencia: "Tiago 1:5", texto: "E, se algum de vós tem falta de sabedoria, peça-a a Deus, que a todos dá liberalmente." },
  { referencia: "Salmos 145:9", texto: "O Senhor é bom para todos, e as suas misericórdias são sobre todas as suas obras." },
  { referencia: "João 14:27", texto: "Deixo-vos a paz, a minha paz vos dou; não se turbe o vosso coração, nem se atemorize." },
  { referencia: "Provérbios 18:10", texto: "Torre forte é o nome do Senhor; a ela correrá o justo, e estará em alto retiro." },
  { referencia: "Salmos 32:8", texto: "Instruir-te-ei, e ensinar-te-ei o caminho que deves seguir; guiar-te-ei com os meus olhos." },
  { referencia: "Romanos 12:12", texto: "Alegrai-vos na esperança, sede pacientes na tribulação, perseverai na oração." },
  { referencia: "Salmos 51:10", texto: "Cria em mim, ó Deus, um coração puro, e renova em mim um espírito reto." },
  { referencia: "Mateus 7:12", texto: "Tudo o que vós quereis que os homens vos façam, fazei-lho também vós a eles." },
  { referencia: "Salmos 133:1", texto: "Oh! quão bom e quão suave é que os irmãos vivam em união." },
  { referencia: "Provérbios 4:23", texto: "Sobre tudo o que se deve guardar, guarda o teu coração, porque dele procedem as saídas da vida." },
  { referencia: "2 Timóteo 1:7", texto: "Porque Deus não nos deu o espírito de temor, mas de fortaleza, e de amor, e de moderação." },
  { referencia: "Salmos 103:2", texto: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios." },
  { referencia: "Isaías 43:2", texto: "Quando passares pelas águas estarei contigo, e quando pelos rios, eles não te submergirão." },
  { referencia: "Salmos 37:4", texto: "Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração." },
  { referencia: "Lucas 6:31", texto: "E, como vós quereis que os homens vos façam, da mesma maneira lhes fazei vós também." },
  { referencia: "Provérbios 27:17", texto: "Como o ferro com o ferro se aguça, assim o homem afia o rosto do seu amigo." },
  { referencia: "Salmos 28:7", texto: "O Senhor é a minha força e o meu escudo; nele confiou o meu coração, e fui socorrido." },
  { referencia: "Filipenses 2:4", texto: "Não atente cada um para o que é propriamente seu, mas cada qual também para o que é dos outros." },
  { referencia: "Salmos 16:8", texto: "Tenho posto o Senhor continuamente diante de mim; por isso que ele está à minha mão direita, nunca vacilarei." },
  { referencia: "Hebreus 13:5", texto: "Contentai-vos com o que tendes; porque ele disse: Não te deixarei, nem te desampararei." },
  { referencia: "Salmos 40:1", texto: "Esperei com paciência no Senhor, e ele se inclinou para mim, e ouviu o meu clamor." },
  { referencia: "Provérbios 12:25", texto: "A ansiedade no coração do homem o abate, mas uma boa palavra o alegra." },
  { referencia: "Mateus 5:16", texto: "Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem o vosso Pai." },
  { referencia: "Salmos 63:1", texto: "Ó Deus, tu és o meu Deus, de madrugada te buscarei; a minha alma tem sede de ti." },
  { referencia: "1 Pedro 5:7", texto: "Lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós." },
  { referencia: "Salmos 143:8", texto: "Faze-me ouvir a tua benignidade pela manhã, pois em ti confio; faze-me saber o caminho que devo seguir." },
  { referencia: "Provérbios 3:6", texto: "Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas." },
  { referencia: "Romanos 15:13", texto: "Ora o Deus de esperança vos encha de todo o gozo e paz em crença, para que abundeis em esperança pela virtude do Espírito Santo." },
  { referencia: "Salmos 90:14", texto: "Farta-nos de madrugada com a tua benignidade, para que nos regozijemos e nos alegremos todos os nossos dias." },
  { referencia: "João 15:12", texto: "O meu mandamento é este: Que vos ameis uns aos outros, assim como eu vos amei." },
  { referencia: "Salmos 34:18", texto: "Perto está o Senhor dos que têm o coração quebrantado, e salva os contritos de espírito." },
  { referencia: "Provérbios 11:25", texto: "A alma generosa prosperará, e aquele que regar também será regado." },
  { referencia: "Efésios 6:10", texto: "Fortalecei-vos no Senhor e na força do seu poder." },
  { referencia: "Salmos 119:105", texto: "Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho." },
  { referencia: "Mateus 19:14", texto: "Deixai os meninos, e não os estorveis de vir a mim; porque dos tais é o reino dos céus." },
  { referencia: "Salmos 62:1", texto: "A minha alma espera somente em Deus; dele vem a minha salvação." },
  { referencia: "Colossenses 3:12", texto: "Revesti-vos de entranhas de misericórdia, de benignidade, humildade, mansidão, longanimidade." },
  { referencia: "Salmos 86:5", texto: "Pois tu, Senhor, és bom, e pronto a perdoar, e abundante em benignidade para todos os que te invocam." },
  { referencia: "Provérbios 16:9", texto: "O coração do homem planeja o seu caminho, mas o Senhor lhe dirige os passos." },
  { referencia: "1 Coríntios 16:14", texto: "Todas as vossas coisas sejam feitas com amor." },
  { referencia: "Salmos 147:3", texto: "Sara os quebrantados de coração, e liga-lhes as feridas." },
  { referencia: "Isaías 26:3", texto: "Tu conservarás em paz aquele cuja mente está firme em ti, porque ele confia em ti." },
  { referencia: "Salmos 138:8", texto: "O Senhor aperfeiçoará o que me concerne; a tua benignidade, ó Senhor, dura para sempre." },
  { referencia: "Gálatas 6:9", texto: "E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se não houvermos desfalecido." },
  { referencia: "Salmos 30:5", texto: "O choro pode durar uma noite, mas a alegria vem pela manhã." },
  { referencia: "Provérbios 19:20", texto: "Ouve o conselho, e recebe a instrução, para que sejas sábio nos teus últimos dias." },
  { referencia: "Mateus 6:34", texto: "Não vos inquieteis, pois, pelo dia de amanhã; porque o dia de amanhã cuidará de si mesmo." },
  { referencia: "Salmos 145:18", texto: "Perto está o Senhor de todos os que o invocam, de todos os que o invocam em verdade." },
  { referencia: "Romanos 12:10", texto: "Amai-vos cordialmente uns aos outros com amor fraternal, preferindo-vos em honra uns aos outros." },
  { referencia: "Salmos 73:26", texto: "A minha carne e o meu coração desfalecem; mas Deus é a força do meu coração, e a minha porção para sempre." },
  { referencia: "Tiago 1:19", texto: "Todo o homem seja pronto para ouvir, tardio para falar, tardio para se irar." },
  { referencia: "Salmos 33:4", texto: "Porque a palavra do Senhor é reta, e todas as suas obras são fiéis." },
  { referencia: "Provérbios 10:12", texto: "O ódio excita contendas, mas o amor cobre todas as transgressões." },
  { referencia: "1 João 3:18", texto: "Meus filhinhos, não amemos de palavra, nem de língua, mas por obra e em verdade." },
  { referencia: "Salmos 112:1", texto: "Bem-aventurado o homem que teme ao Senhor, que em seus mandamentos tem grande prazer." },
  { referencia: "Isaías 41:13", texto: "Porque eu, o Senhor teu Deus, te tomo pela tua mão direita, e te digo: Não temas, eu te ajudo." },
  { referencia: "Salmos 84:11", texto: "O Senhor Deus é sol e escudo; o Senhor dará graça e glória; não negará bem algum aos que andam na retidão." },
  { referencia: "Provérbios 3:27", texto: "Não detenhas o bem daquele a quem é devido, estando na tua mão o poder de o fazer." },
];

// Índice determinístico pelo dia do calendário local: mesma passagem o dia
// inteiro, avançando uma por dia e voltando ao início ao fim da lista.
export function versiculoDoDia(data: Date = new Date()): Versiculo {
  const dias = Math.floor(
    Date.UTC(data.getFullYear(), data.getMonth(), data.getDate()) / 86400000,
  );
  const indice = ((dias % VERSICULOS.length) + VERSICULOS.length) % VERSICULOS.length;
  return VERSICULOS[indice];
}
